### ISSUE TITLE
Crashed when clearing bold text 

### ISSUE THREAD

**Issue by prasid444** [raralabs/rara-rte#45]
**Description**
The web crashed while writing and clearing bold text.

**To Reproduce**
1. Write some text in multiple lines
2. Select any line with empty text
3. Make it bold
4. Hit Delete to clear text

**Expected behavior**
The bold line should be removed without crash

**Additional context**

```
index.90882525.js:328 Error: Cannot find a descendant at path [0,-1] in node: {"children":[{"type":"paragraph","children":[{"text":"T"}]},{"type":"paragraph","children":[{"bold":true,"text":""}]}],"operations":[],"selection":{"anchor":{"path":[0,-1],"offset":0},"focus":{"path":[0,-1],"offset":0}},"marks":null,"history":{"undos":[[{"type":"set_selection","properties":{"anchor":{"path":[4,0],"offset":193},"focus":{"path":[4,0],"offset":193}},"newProperties":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[9,0],"offset":6}}}],[{"type":"remove_text","path":[0,0],"offset":0,"text":"An integration framework i"},{"type":"remove_node","path":[8],"node":{"type":"paragraph","children":[{"text":"\n\n\n\n\n\n"}]}},{"type":"remove_node","path":[7],"node":{"type":"paragraph","children":[{"text":"Integration frameworks typically include a range of features and capabilities, such as data mapping, message routing, transformation, security, and monitoring. By providing a standardized approach to integration, these frameworks help organizations to reduce the time and cost of integrating systems, while also improving data accuracy and consistency."}]}},{"type":"remove_node","path":[6],"node":{"type":"numbered-list","children":[{"text":""}]}},{"type":"remove_node","path":[5],"node":{"type":"paragraph","children":[{"text":"There are several types of integration frameworks, including:"}]}},{"type":"remove_node","path":[4],"node":{"type":"paragraph","children":[{"text":"An integration framework is a set of tools, technologies, and best practices used to facilitate the integration of different systems and applications. The goal of an integration framework is to simplify the process of connecting systems, making it easier to exchange data and perform actions across different environments."}]}},{"type":"remove_node","path":[3],"node":{"type":"paragraph","children":[{"text":""},{"type":"link","url":"https://www.figma.com/file/0hUed8I58krowYUJAIheJm/IntellixPOC_System_Design?node-id=5312-1860&t=DVCkbUqX2qz92xVz-0","children":[{"text":"https://www.figma.com/file/0hUed8I58krowYUJAIheJm/IntellixPOC_System_Design?node-id=5312-1860&t=DVCkbUqX2qz92xVz-0"}]},{"text":"\n"}]}},{"type":"remove_node","path":[2],"node":{"type":"paragraph","children":[{"text":"Integration frameworks typi","bold":true},{"text":"cally include a range of features and capabilities, such as data mapping, message routing, transformation, security, and monitoring. By providing a standardized approach to integration, these frameworks help organizations to reduce the time and cost of integrating systems, while also improving data accuracy and consistency."}]}},{"type":"remove_node","path":[1],"node":{"type":"paragraph","children":[{"text":"There are several types of integration frameworks, including:\n"}]}},{"type":"remove_node","path":[0,1],"node":{"text":"s a set of tools, technologies, and best practices used to facilitate the integration of different systems and applications. The goal of an integration framework is to simplify the process of connecting systems, making it easier to exchange data and perform actions across different environments."}},{"type":"remove_text","path":[1,0],"offset":0,"text":"\n\n\n\n\n\n"},{"type":"remove_node","path":[0],"node":{"type":"paragraph","children":[{"text":"","bold":true}]}}],[{"type":"insert_text","path":[0,0],"offset":0,"text":"T"},{"type":"insert_text","path":[0,0],"offset":1,"text":"h"}],[{"type":"remove_text","path":[0,0],"offset":1,"text":"h"},{"type":"remove_text","path":[0,0],"offset":0,"text":"T"}],[{"type":"set_node","path":[0,0],"properties":{},"newProperties":{"bold":true}}],[{"type":"insert_text","path":[0,0],"offset":0,"text":"T"},{"type":"insert_text","path":[0,0],"offset":1,"text":"h"},{"type":"insert_text","path":[0,0],"offset":2,"text":"i"},{"type":"insert_text","path":[0,0],"offset":3,"text":"s"},{"type":"insert_text","path":[0,0],"offset":4,"text":" "},{"type":"insert_text","path":[0,0],"offset":5,"text":"W"},{"type":"insert_text","path":[0,0],"offset":6,"text":"e"},{"type":"insert_text","path":[0,0],"offset":7,"text":"e"},{"type":"insert_text","path":[0,0],"offset":8,"text":"k"},{"type":"insert_text","path":[0,0],"offset":9,"text":" "},{"type":"insert_text","path":[0,0],"offset":10,"text":":"},{"type":"insert_text","path":[0,0],"offset":11,"text":" "},{"type":"insert_text","path":[0,0],"offset":12,"text":"("},{"type":"insert_text","path":[0,0],"offset":13,"text":"1"},{"type":"insert_text","path":[0,0],"offset":14,"text":"s"},{"type":"insert_text","path":[0,0],"offset":15,"text":"t"},{"type":"insert_text","path":[0,0],"offset":16,"text":" "},{"type":"insert_text","path":[0,0],"offset":17,"text":"m"},{"type":"insert_text","path":[0,0],"offset":18,"text":"a"},{"type":"insert_text","path":[0,0],"offset":19,"text":"y"},{"type":"insert_text","path":[0,0],"offset":20,"text":" "},{"type":"insert_text","path":[0,0],"offset":21,"text":"t"},{"type":"insert_text","path":[0,0],"offset":22,"text":"o"},{"type":"insert_text","path":[0,0],"offset":23,"text":" "},{"type":"insert_text","path":[0,0],"offset":24,"text":"4"},{"type":"insert_text","path":[0,0],"offset":25,"text":"t"},{"type":"insert_text","path":[0,0],"offset":26,"text":"h"},{"type":"insert_text","path":[0,0],"offset":27,"text":" "},{"type":"insert_text","path":[0,0],"offset":28,"text":"M"},{"type":"insert_text","path":[0,0],"offset":29,"text":"a"},{"type":"insert_text","path":[0,0],"offset":30,"text":"y"}],[{"type":"remove_text","path":[0,0],"offset":30,"text":"y"},{"type":"remove_text","path":[0,0],"offset":29,"text":"a"},{"type":"remove_text","path":[0,0],"offset":28,"text":"M"},{"type":"remove_text","path":[0,0],"offset":27,"text":" "}],[{"type":"insert_text","path":[0,0],"offset":27,"text":" "},{"type":"insert_text","path":[0,0],"offset":28,"text":"m"},{"type":"insert_text","path":[0,0],"offset":29,"text":"a"},{"type":"insert_text","path":[0,0],"offset":30,"text":"y"},{"type":"insert_text","path":[0,0],"offset":31,"text":")"}],[{"type":"split_node","path":[0,0],"position":32,"properties":{"bold":true}},{"type":"split_node","path":[0],"position":1,"properties":{"type":"paragraph"}}],[{"type":"insert_text","path":[1,0],"offset":0,"text":"-"},{"type":"insert_text","path":[1,0],"offset":1,"text":" "}],[{"type":"remove_text","path":[1,0],"offset":1,"text":" "},{"type":"remove_text","path":[1,0],"offset":0,"text":"-"},{"type":"set_selection","properties":{"focus":{"path":[0,0],"offset":8}},"newProperties":{"focus":{"path":[0,0],"offset":0}}}],[{"type":"remove_text","path":[0,0],"offset":0,"text":"This Week : (1st may to 4th may)"}],[{"type":"insert_node","path":[0,1],"node":{"text":"T"}},{"type":"set_selection","properties":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}},"newProperties":{"anchor":{"path":[0,1],"offset":1},"focus":{"path":[0,1],"offset":1}}},{"type":"remove_node","path":[0,0],"node":{"text":"","bold":true}},{"type":"set_selection","properties":{"anchor":{"path":[0,1],"offset":0},"focus":{"path":[0,1],"offset":0}},"newProperties":{"anchor":{"path":[0,-1],"offset":0},"focus":{"path":[0,-1],"offset":0}}}]],"redos":[]}}
    at Object.get (index.90882525.js:5571:8426)
    at Object.nodes (index.90882525.js:5571:10118)
    at nodes.next (<anonymous>)
    at Object.nodes (index.90882525.js:5569:46540)
    at nodes.next (<anonymous>)
    at Function.from (<anonymous>)
    at ct (index.90882525.js:5580:25304)
    at ct (index.90882525.js:5582:12581)
    at Xh (index.90882525.js:326:21738)
    at Wk (index.90882525.js:328:48870)
Mi @ index.90882525.js:328

```

**Comment by prasid444** [comment]
Resolved in #43
